---- Table: Excercise
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (1, 'Bench Press', NULL, NULL, NULL, NULL, NULL, 1554392334, NULL, 1, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (2, 'Bench Press - Inclined', NULL, NULL, NULL, NULL, NULL, 1554392354, NULL, 1, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (3, 'Bench Press - Dumbell', NULL, NULL, NULL, NULL, NULL, 1554392398, NULL, 1, 3, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (4, 'Cable Flyes', NULL, NULL, NULL, NULL, NULL, 1554392418, NULL, 1, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (5, 'Pec Dec', NULL, NULL, NULL, NULL, NULL, 1554392429, NULL, 1, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (6, 'Dips', NULL, NULL, NULL, NULL, NULL, 1554392445, NULL, 1, 7, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (7, 'Squat', NULL, NULL, NULL, NULL, NULL, 1554392507, NULL, 10, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (8, 'Front Squat', NULL, NULL, NULL, NULL, NULL, 1554392507, NULL, 10, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (9, 'Overhead Squat', NULL, NULL, NULL, NULL, NULL, 1554392507, NULL, 10, 1, 1, 3);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (10, 'Leg Extensions', NULL, NULL, NULL, NULL, NULL, 1554392518, NULL, 10, 1, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (11, 'Sommersault Squat - Smith Machine', NULL, NULL, NULL, NULL, NULL, 1554392590, NULL, 10, 7, 1, 3);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (12, 'Sissy Squat', NULL, NULL, NULL, NULL, NULL, 1554392590, NULL, 10, 8, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (13, 'Military Press', NULL, NULL, NULL, NULL, NULL, 1554392654, NULL, 2, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (14, 'Overhead Press - Dumbell', NULL, NULL, NULL, NULL, NULL, 1554392654, NULL, 2, 3, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (15, 'Lateral Raises', NULL, NULL, NULL, NULL, NULL, 1554392654, NULL, 2, 3, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (16, 'Overhead Press Machine', NULL, NULL, NULL, NULL, NULL, 1554392654, NULL, 2, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (17, 'Shrugs - Barbell', NULL, NULL, NULL, NULL, NULL, 1554392711, NULL, 6, 1, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (18, 'Shrugs - Dumbell', NULL, NULL, NULL, NULL, NULL, 1554392711, NULL, 6, 3, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (19, 'Shrugs on inclined bench', NULL, NULL, NULL, NULL, NULL, 1554392711, NULL, 6, 3, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (20, 'Pullups', NULL, NULL, NULL, NULL, NULL, 1554392816, NULL, 7, 8, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (21, 'Lat Machine', NULL, NULL, NULL, NULL, NULL, 1554392816, NULL, 7, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (22, 'Lat Machine - Reverse grip', NULL, NULL, NULL, NULL, NULL, 1554392816, NULL, 7, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (23, 'Pulldowns', NULL, NULL, NULL, NULL, NULL, 1554392816, NULL, 7, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (24, 'Barbell Row', NULL, NULL, NULL, NULL, NULL, 1554392816, NULL, 7, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (25, 'Romanian Deadlifts', NULL, NULL, NULL, NULL, NULL, 1554392893, NULL, 11, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (26, 'Leg Curl - Lying', NULL, NULL, NULL, NULL, NULL, 1554392893, NULL, 11, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (27, 'Leg Curl - Seated', NULL, NULL, NULL, NULL, NULL, 1554392893, NULL, 11, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (28, 'Deadlifts', NULL, NULL, NULL, NULL, NULL, 1554392893, NULL, 11, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (29, 'Nordic Ham Raises', NULL, NULL, NULL, NULL, NULL, 1554392915, NULL, 11, 8, 1, 3);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (30, 'French Press', NULL, NULL, NULL, NULL, NULL, 1554392999, NULL, 4, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (31, 'Skullcrusher', NULL, NULL, NULL, NULL, NULL, 1554392999, NULL, 4, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (32, 'Triceps Cable Extensions', NULL, NULL, NULL, NULL, NULL, 1554392999, NULL, 4, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (33, 'Triceps Dips', NULL, NULL, NULL, NULL, NULL, 1554392999, NULL, 4, 6, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (34, 'Cable Curl', NULL, NULL, NULL, NULL, NULL, 1554393053, NULL, 3, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (35, 'Dumbell Curl', NULL, NULL, NULL, NULL, NULL, 1554393053, NULL, 3, 3, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (36, 'Lat Machine behind the neck', NULL, NULL, NULL, NULL, NULL, 1554393053, NULL, 3, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (37, 'Seated Calvees - Smith Machine', NULL, NULL, NULL, NULL, NULL, 1554393135, NULL, 13, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (38, 'Standing Calves Machine', NULL, NULL, NULL, NULL, NULL, 1554393135, NULL, 13, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (39, 'Squatting Calves - Smith Machine', NULL, NULL, NULL, NULL, NULL, 1554393135, NULL, 13, 7, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (40, 'Calves on lg press', NULL, NULL, NULL, NULL, NULL, 1554393135, NULL, 13, 7, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (41, 'Seated Calves - Barbell', NULL, NULL, NULL, NULL, NULL, 1554393135, NULL, 13, 1, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (42, 'Hip Thrust', NULL, NULL, NULL, NULL, NULL, 1554393197, NULL, 9, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (43, 'Frog Pump', NULL, NULL, NULL, NULL, NULL, 1554393197, NULL, 9, 8, 1, 1);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (44, 'Sumo Squat', NULL, NULL, NULL, NULL, NULL, 1554393197, NULL, 9, 1, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (45, 'Sumo Squat - Dumbell', NULL, NULL, NULL, NULL, NULL, 1554393197, NULL, 9, 3, 1, 2);
--INSERT INTO Excercise (Id, Name, Description, ExecutionGuide, CriticalPointsDescription, ImageUrl, IsApproved, CreatedOn, LastUpdate, MuscleId, TrainingEquipmentId, OwnerId, ExcerciseDifficultyId) VALUES (46, 'Hip Thrust - Leg Extension', NULL, NULL, NULL, NULL, NULL, 1554393219, NULL, 9, 7, 1, 1);




-- Table: Excercise
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (1, 'Bench Press', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (2, 'Bench Press - Inclined', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (3, 'Bench Press - Dumbell', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (4, 'Cable Flyes', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (5, 'Pec Dec', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (6, 'Dips', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (7, 'Squat', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (8, 'Front Squat', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (9, 'Overhead Squat', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (10, 'Leg Extensions', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (11, 'Sommersault Squat - Smith Machine', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (12, 'Sissy Squat', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (13, 'Military Press', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (14, 'Overhead Press - Dumbell', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (15, 'Lateral Raises', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (16, 'Overhead Press Machine', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (17, 'Shrugs - Barbell', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (18, 'Shrugs - Dumbell', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (19, 'Shrugs on inclined bench', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (20, 'Pullups', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (21, 'Lat Machine', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (22, 'Lat Machine - Reverse grip', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (23, 'Pulldowns', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (24, 'Barbell Row', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (25, 'Romanian Deadlifts', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (26, 'Leg Curl - Lying', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (27, 'Leg Curl - Seated', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (28, 'Deadlifts', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (29, 'Nordic Ham Raises', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (30, 'French Press', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (31, 'Skullcrusher', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (32, 'Triceps Cable Extensions', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (33, 'Triceps Dips', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (34, 'Cable Curl', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (35, 'Dumbell Curl', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (36, 'Lat Machine behind the neck', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (37, 'Seated Calvees - Smith Machine', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (38, 'Standing Calves Machine', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (39, 'Squatting Calves - Smith Machine', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (40, 'Calves on lg press', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (41, 'Seated Calves - Barbell', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (42, 'Hip Thrust', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (43, 'Frog Pump', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (44, 'Sumo Squat', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (45, 'Sumo Squat - Dumbell', "Dummy Description", 5);
INSERT INTO Excercise (Id, Name, Description, EntryStatusId) VALUES (46, 'Hip Thrust - Leg Extension', "Dummy Description", 5);

